import type { TypedFlatConfigItem } from "@antfu/eslint-config";

export default {
  name: "ilyasso/eslint",
  rules: {
    camelcase: "warn",
    // 'consistent-return': 'warn', // conflict with 'unicorn/no-useless-undefined'
    "default-param-last": "warn",
    "for-direction": "warn",
    "func-style": ["warn", "declaration", { allowArrowFunctions: true }],
    "no-await-in-loop": "warn",
    "no-bitwise": "warn",
    "no-constant-binary-expression": "warn",
    "no-constant-condition": "warn",
    "no-constructor-return": "warn",
    "no-div-regex": "warn",
    "no-dupe-else-if": "warn",
    "no-duplicate-imports": ["warn", { allowSeparateTypeImports: true }],
    "no-else-return": "warn",
    "no-empty-function": "warn",
    "no-empty-static-block": "warn",
    "no-eq-null": "warn",
    "no-extra-label": "warn",
    "no-implicit-coercion": "warn",
    "no-implicit-globals": "warn",
    "no-inner-declarations": ["warn", "both"],
    "no-invalid-this": "warn",
    "no-label-var": "warn",
    "no-lonely-if": "warn",
    "no-loop-func": "warn",
    "no-magic-numbers": ["warn", { ignore: [-1, 0, 1, 2, 10] }],
    "no-multi-assign": "warn",
    "no-negated-condition": "warn",
    "no-nested-ternary": "warn",
    "no-nonoctal-decimal-escape": "warn",
    "no-object-constructor": "warn",
    "no-param-reassign": "warn",
    "no-promise-executor-return": "warn",
    "no-return-assign": "warn",
    "no-script-url": "warn",
    "no-shadow": "warn",
    "no-unassigned-vars": "warn",
    "no-underscore-dangle": "warn",
    "no-unsafe-optional-chaining": "warn",
    "no-unused-private-class-members": "warn",
    "no-useless-assignment": "warn",
    "no-useless-concat": "warn",
    "no-useless-escape": "warn",
    "no-void": ["warn", { allowAsStatement: true }],
    "operator-assignment": "warn",
    "prefer-destructuring": "warn",
    "prefer-numeric-literals": "warn",
    "prefer-object-has-own": "warn",
    "prefer-object-spread": "warn",
    "require-atomic-updates": "warn",
    "require-await": "warn",
    "require-unicode-regexp": "warn",
    "require-yield": "warn",

    "no-console": "warn",

    "perfectionist/sort-imports": "off",
    "no-useless-return": "off",

    // Overrides
    "array-callback-return": [
      "error",
      {
        allowImplicit: true,
      },
    ],
  },
} as TypedFlatConfigItem;
