import type { TypedFlatConfigItem } from "@antfu/eslint-config";

export default {
  name: "ilyasso/eslint",
  files: ["**/*.ts", "**/*.tsx", "**/*.vue"],
  rules: {
    camelcase: "warn",
    "arrow-body-style": ["warn", "as-needed"],
    curly: ["warn", "all"],
    // 'consistent-return': 'warn', // conflict with 'unicorn/no-useless-undefined'
    "default-param-last": "warn",
    "for-direction": "error",
    "func-style": ["warn", "declaration", { allowArrowFunctions: true }],
    "func-names": "warn",
    "grouped-accessor-pairs": ["warn", "getBeforeSet"],
    "logical-assignment-operators": "warn",
    "no-bitwise": "warn",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-constructor-return": "error",
    "no-div-regex": "warn",
    "no-dupe-else-if": "error",
    "no-duplicate-imports": ["warn", { allowSeparateTypeImports: true }],
    "no-else-return": "warn",
    "no-empty-function": "warn",
    "no-empty-static-block": "warn",
    "no-extra-label": "warn",
    "no-implicit-coercion": "warn",
    "no-implicit-globals": "warn",
    "no-inner-declarations": ["warn", "both"],
    "no-invalid-this": "warn",
    "no-label-var": "warn",
    "no-lonely-if": "warn",
    "no-loop-func": "warn",
    "no-magic-numbers": [
      "warn",
      {
        ignore: [-1, 0, 1, 2, 10],
        ignoreArrayIndexes: true,
        ignoreDefaultValues: true,
        ignoreEnums: true,
        ignoreClassFieldInitialValues: true,
        ignoreReadonlyClassProperties: true,
      },
    ],
    "no-multi-assign": "warn",
    "no-nested-ternary": "warn",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "warn",
    "no-object-constructor": "warn",
    "no-param-reassign": "warn",
    "no-promise-executor-return": "error",
    "no-return-assign": "warn",
    "no-script-url": "warn",
    "no-shadow": "warn",
    "no-unassigned-vars": "error",
    "no-underscore-dangle": "warn",
    "no-unsafe-optional-chaining": "error",
    "no-unused-private-class-members": "warn",
    "no-useless-assignment": "error",
    "no-useless-concat": "warn",
    "no-useless-escape": "warn",
    "no-void": ["warn", { allowAsStatement: true }],
    "operator-assignment": "warn",
    "prefer-destructuring": "warn",
    "prefer-numeric-literals": "warn",
    "prefer-object-has-own": "warn",
    "prefer-object-spread": "warn",
    "require-atomic-updates": "warn",
    "require-await": "warn",
    "require-unicode-regexp": "warn",
    "require-yield": "error",

    "no-console": ["warn", { allow: ["warn", "error"] }],
    "no-useless-return": "warn",

    "perfectionist/sort-imports": "off",

    // Overrides
    "array-callback-return": [
      "error",
      {
        allowImplicit: true,
      },
    ],
  },
} as TypedFlatConfigItem;
